<?php if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
'key' => 'group_578877343cec9',
'title' => 'locations',
'fields' => array (
  array (
    'key' => 'field_5788773b5fa5a',
    'label' => 'Logo',
    'name' => 'logo',
    'type' => 'image',
    'instructions' => '',
    'required' => 0,
    'conditional_logic' => 0,
    'wrapper' => array (
      'width' => '',
      'class' => '',
      'id' => '',
    ),
    'return_format' => 'url',
    'preview_size' => 'medium',
    'library' => 'all',
    'min_width' => '',
    'min_height' => '',
    'min_size' => '',
    'max_width' => '',
    'max_height' => '',
    'max_size' => '',
    'mime_types' => '',
  ),
  array (
    'key' => 'field_578877525fa5b',
    'label' => 'Additional Image',
    'name' => 'additional_image',
    'type' => 'image',
    'instructions' => '',
    'required' => 0,
    'conditional_logic' => 0,
    'wrapper' => array (
      'width' => '',
      'class' => '',
      'id' => '',
    ),
    'return_format' => 'url',
    'preview_size' => 'medium',
    'library' => 'all',
    'min_width' => '',
    'min_height' => '',
    'min_size' => '',
    'max_width' => '',
    'max_height' => '',
    'max_size' => '',
    'mime_types' => '',
  ),
  array (
    'key' => 'field_578877e25fa5c',
    'label' => 'Map',
    'name' => 'map',
    'type' => 'google_map',
    'instructions' => '',
    'required' => 0,
    'conditional_logic' => 0,
    'wrapper' => array (
      'width' => '',
      'class' => '',
      'id' => '',
    ),
    'center_lat' => '',
    'center_lng' => '',
    'zoom' => '',
    'height' => '',
  ),
),
'location' => array (
  array (
    array (
      'param' => 'post_type',
      'operator' => '==',
      'value' => 'location',
    ),
  ),
),
'menu_order' => 0,
'position' => 'acf_after_title',
'style' => 'default',
'label_placement' => 'top',
'instruction_placement' => 'label',
'hide_on_screen' => '',
'active' => 1,
'description' => '',
));

endif;

?>
